### ISSUE TITLE
AlertBlockExtension(configs=configs)

### ISSUE THREAD

**Issue by simonrenger** [Saevon/mdx_alerts#1]
I installed the extension like described and the I run into this issue
```
Traceback (most recent call last):
  File "a:\program files (x86)\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "a:\program files (x86)\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "A:\Program Files (x86)\Python\Scripts\mkdocs.exe\__main__.py", line 9, in <module>
  File "a:\program files (x86)\python\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "a:\program files (x86)\python\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "a:\program files (x86)\python\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "a:\program files (x86)\python\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "a:\program files (x86)\python\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "a:\program files (x86)\python\lib\site-packages\mkdocs\__main__.py", line 127, in serve_command
    livereload=livereload
  File "a:\program files (x86)\python\lib\site-packages\mkdocs\commands\serve.py", line 117, in serve
    config = builder()
  File "a:\program files (x86)\python\lib\site-packages\mkdocs\commands\serve.py", line 112, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "a:\program files (x86)\python\lib\site-packages\mkdocs\commands\build.py", line 282, in build
    build_pages(config, dirty=dirty)
  File "a:\program files (x86)\python\lib\site-packages\mkdocs\commands\build.py", line 242, in build_pages
    _build_page(page, config, site_navigation, env)
  File "a:\program files (x86)\python\lib\site-packages\mkdocs\commands\build.py", line 137, in _build_page
    page.render(config, site_navigation)
  File "a:\program files (x86)\python\lib\site-packages\mkdocs\nav.py", line 293, in render
    extension_configs=config['mdx_configs'] or {}
  File "a:\program files (x86)\python\lib\site-packages\markdown\__init__.py", line 159, in __init__
    configs=kwargs.get('extension_configs', {}))
  File "a:\program files (x86)\python\lib\site-packages\markdown\__init__.py", line 185, in registerExtensions
    ext = self.build_extension(ext, configs.get(ext, {}))
  File "a:\program files (x86)\python\lib\site-packages\markdown\__init__.py", line 291, in build_extension
    return module.makeExtension(**configs)
  File "a:\program files (x86)\python\lib\site-packages\mdx_alerts.py", line 164, in makeExtension
    return AlertBlockExtension(configs=configs)
  File "a:\program files (x86)\python\lib\site-packages\markdown\extensions\__init__.py", line 51, in __init__
    self.setConfigs(kwargs)
  File "a:\program files (x86)\python\lib\site-packages\markdown\extensions\__init__.py", line 82, in setConfigs
    self.setConfig(key, value)
  File "a:\program files (x86)\python\lib\site-packages\markdown\extensions\__init__.py", line 70, in setConfig
    if isinstance(self.config[key][0], bool):
KeyError: 'configs'
```
This is actual the intersting line:
```
  File "a:\program files (x86)\python\lib\site-packages\mdx_alerts.py", line 164, in makeExtension
    return AlertBlockExtension(configs=configs)
```

I have fixed this by:

```python
def makeExtension(*args,**kwargs):
    return MarkdownIncludeLines(kwargs)
```

**Comment by Saevon** [comment]
This was a problem with Markdown updating, I've solved it in my repo as well, so feel free to pull.

Thanks! (Technically I use Markdown 2.4, if any other compatibility problems occur I'll try to update it)

**Comment by Saevon** [comment]
@simonrenger  Also, the proper solution is the following (in case you don't end up pulling the code)
```
def makeExtension(*args, **kwargs):
    return AlertBlockExtension(*args, **kwargs)
```
